spring:
  application:
    name: pointtrack
  profiles:
    active: dev,local
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
